### ISSUE TITLE
isVisible() / isNotVisible() throw error with HTMLElement as parameter

### ISSUE THREAD

**Issue by woprandi** [simplabs/qunit-dom#508] opened 2019-10-11 09:55 UTC
Hi,

`isVisible()` and` isNotVisible() `throw an error if the parameter is a DOM node

```
// WORKS
assert.dom(".foo").isVisible() 

// THROW ERROR
assert.dom(document.querySelector(".foo")).isVisible()
```

other assertions like `hasText` / `hasValue` accept HTMLElement as parameter.

**Comment by scalvert** [comment] 2019-10-11 15:18
Duplicate of #245.

**Closed by scalvert** 2019-10-11 15:18 UTC
