### ISSUE TITLE
Add isChecked() assertion 

### ISSUE THREAD

**Issue by martndemus** [simplabs/qunit-dom#51] opened 2018-02-09 13:55 UTC
That would be great!

**Comment by Turbo87** [comment] 2018-02-09 14:00
I guess this is a duplicate of https://github.com/simplabs/qunit-dom/issues/38, but more focused on a single assertion, so I'll keep this open. PRs obviously welcome 😉

**Comment by martndemus** [comment] 2018-02-09 14:02
🤦‍♀️ oops, did not check the issues well enough. Sorry about that!

**Comment by Turbo87** [comment] 2018-02-09 14:03
no worries, the other issue doesn't have a particularly expressive title 😉

**Closed** 2018-03-12 19:12 UTC
Labels: beginner-friendly, enhancement
