### ISSUE TITLE
assert.dom(undefined).exists() does not throw, returns true

### ISSUE THREAD

**Issue by diephx** [simplabs/qunit-dom#771] opened 2020-07-29 17:56 UTC
It feels strange that the following assertions do not throw errors, but instead returns true:
```
assert.dom(undefined).exists(); // does not throw, returns true
assert.dom(null).exists(); // does not throw, returns true
assert.dom(undefined).isVisible(); // throws
assert.dom(null).isVisible(); // does not throw, returns true
```

Is this a bug or expected? I might be missing a few other assertions which are affected.

@Turbo87 do you have better context as to why we allowed undefined or null
https://github.com/simplabs/qunit-dom/issues/57

Here's the commit that added the feature:
https://github.com/simplabs/qunit-dom/commit/f056786526a708a6716692e345558d4b6a7ba749#diff-79a22eedafdf2345b85d18f3d593f474

**Comment by scalvert** [comment] 2020-07-29 18:25
Thanks for reporting, @diephx. I'd also be interested in the reasoning here.

It's clear it was implemented early on. I'd be curious to know if this functionality still stands as a valid path for invocation.

**Comment by Turbo87** [comment] 2020-07-30 09:07
This is a duplicate of #736

> do you have better context as to why we allowed undefined or null

It's a bug. `assert.dom()` should be allowed to work and default to the `rootElement`, but `null` or `undefined` was never supposed to default to the `rootElement`

**Closed by Turbo87** 2020-07-30 09:07 UTC
Labels: question
